version = 0.1

[default.global.parameters]
stack_name = "employees-api"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "employees-api"
s3_prefix = "employees-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
template_file = "employees-api/template.yaml"
